<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A fully customizable and extensible all-purpose diagrams library for Blazor</Description>
    <PackageId>Stromlab.Blazor.Diagrams.Core</PackageId>
    <PackageTags>blazor diagrams diagramming svg drag</PackageTags>
    <Product>Stromlab.Blazor.Diagrams.Core</Product>
    <PackageIcon>ZBD.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\ZBD.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SvgPathProperties" />
  </ItemGroup>

</Project>
