<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Algorithms for Stromlab.Blazor.Diagrams</Description>
    <PackageId>Stromlab.Blazor.Diagrams.Algorithms</PackageId>
    <PackageTags>blazor diagrams diagramming svg drag algorithms layouts</PackageTags>
    <Product>Stromlab.Blazor.Diagrams.Algorithms</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blazor.Diagrams.Core\Blazor.Diagrams.Core.csproj" />
  </ItemGroup>

</Project>
