<Project>
  <PropertyGroup>
    <TargetFrameworks>net9.0;net8.0;net7.0;net6.0;</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

    <PackageProjectUrl>https://github.com/Greexter/Blazor.Diagrams</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Greexter/Blazor.Diagrams</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>zHaytam, Jakub Štrom</Authors>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <ArtifactsPath>$(MSBuildThisFileDirectory)../artifacts</ArtifactsPath>
  </PropertyGroup>

  <ItemGroup Label="MinVer">
    <PackageReference Include="MinVer" PrivateAssets="All" />
  </ItemGroup>
</Project>
